name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  ARDA_VERSION: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build Docker Image
        run: |
          docker build --target builder --build-arg ARDA_VERSION=${{ env.ARDA_VERSION }} -t play-mume-builder .
      - name: Extract Build Artifacts
        run: |
          docker create --name temp-container play-mume-builder
          docker cp temp-container:/usr/src/app/dist ./dist
          docker rm temp-container
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
